# Generated by Django 3.0.4 on 2020-03-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='usuario',
            new_name='owner',
        ),
    ]
